ml_scripts_dir: "/home/kousis/Predict_cultivars/ml"
output_dir: "/home/kousis/Documents"
vcf_input: "/home/kousis/Predict_cultivars/test.vcf"
enable_imputation: true
beagle_file: "/home/kousis/Desktop/beagle.17Dec24.224.jar"
wanted_positions_panel: "/home/kousis/Predict_cultivars/imputed_filtered.vcf"
ml_algorithm: "algorithm2"
bed_file_algorithm2: "/home/kousis/Predict_cultivars/bed/top_30_hotspots.bed"
